name: Simple GitHub Action
on: [push, pull_request]

jobs:
  check-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "Automatisation réussie !"
